apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: ai-model-registry
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.47
          ports:
            - containerPort: 16686
              name: ui
            - containerPort: 14268
              name: collector
            - containerPort: 6831
              name: agent-udp
              protocol: UDP
            - containerPort: 6832
              name: agent-binary
            - containerPort: 5778
              name: agent-config
          env:
            - name: COLLECTOR_ZIPKIN_HOST_PORT
              value: ":9411"
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: "/"
              port: 14269
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: "/"
              port: 14269
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: ai-model-registry
  labels:
    app: jaeger
spec:
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
    - name: collector
      port: 14268
      targetPort: 14268
    - name: agent-udp
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: agent-binary
      port: 6832
      targetPort: 6832
    - name: agent-config
      port: 5778
      targetPort: 5778
  selector:
    app: jaeger
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: ai-model-registry
  labels:
    app: jaeger
spec:
  ports:
    - name: agent-udp
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: agent-binary
      port: 6832
      targetPort: 6832
    - name: agent-config
      port: 5778
      targetPort: 5778
  selector:
    app: jaeger
  type: ClusterIP