{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-model-registry.fullname" . }}-api-gateway
  labels:
    {{- include "ai-model-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ai-model-registry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
{{- end }}