{{- range $serviceName, $serviceConfig := .Values.backend }}
{{- if $serviceConfig.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-model-registry.fullname" $ }}-{{ $serviceName }}
  labels:
    {{- include "ai-model-registry.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  type: {{ $serviceConfig.service.type }}
  ports:
    - port: {{ $serviceConfig.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ai-model-registry.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
{{- end }}
{{- end }}