{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ai-model-registry.fullname" . }}-frontend
  labels:
    {{- include "ai-model-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ai-model-registry.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
---
{{- range $serviceName, $serviceConfig := .Values.backend }}
{{- if $serviceConfig.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ai-model-registry.fullname" $ }}-{{ $serviceName }}
  labels:
    {{- include "ai-model-registry.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  {{- if $.Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if $.Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ $.Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ai-model-registry.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $serviceName }}
---
{{- end }}
{{- end }}
{{- end }}