{{- if and .Values.monitoring.prometheus.enabled .Values.monitoring.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ai-model-registry.fullname" . }}-frontend
  labels:
    {{- include "ai-model-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      {{- include "ai-model-registry.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.prometheus.serviceMonitor.interval }}
---
{{- range $serviceName, $serviceConfig := .Values.backend }}
{{- if $serviceConfig.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ai-model-registry.fullname" $ }}-{{ $serviceName }}
  labels:
    {{- include "ai-model-registry.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  selector:
    matchLabels:
      {{- include "ai-model-registry.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $serviceName }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ $.Values.monitoring.prometheus.serviceMonitor.interval }}
---
{{- end }}
{{- end }}
{{- if .Values.apiGateway.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ai-model-registry.fullname" . }}-api-gateway
  labels:
    {{- include "ai-model-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  selector:
    matchLabels:
      {{- include "ai-model-registry.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.prometheus.serviceMonitor.interval }}
{{- end }}
{{- end }}