apiVersion: v2
name: ai-model-registry
description: A Helm chart for AI Model Registry platform
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - ai
  - ml
  - model-registry
  - governance
home: https://github.com/your-org/ai-model-registry
sources:
  - https://github.com/your-org/ai-model-registry
maintainers:
  - name: AI Model Registry Team
    email: team@yourorg.com
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled